### ISSUE TITLE
Question: Where to put that command?

### ISSUE THREAD

**Issue by ghost** [uwolf/jekyll-i18n-date#1]
Hello, sorry for disturbing you. I don't know where to put that command below:
```
 {{ page.date | localize: "%d.%m.%Y" }}
```
Can you help me?

**Comment by nxjosephofficial** [comment]
I don't need that anymore because i've changed my jekyll theme.

**Comment by nxjosephofficial** [comment]
I don't need that anymore because i've changed my jekyll theme.

**Comment by nxjosephofficial** [comment]
I don't need that anymore because i've changed my jekyll theme.

**Comment by ghost** [comment]
I don't need that anymore because i've changed my jekyll theme.
